import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react';
import { AlertTriangle, ArrowUp, Check, ClipboardPlus, Database, Eraser, LoaderCircle, MessageSquareText, ShieldCheck, Sparkles, Truck, UserRound, X } from 'lucide-react';
import { api, roleLabel, type User } from '../api';
import type { Driver,Vehicle } from '../types';

type Evidence={tool:string;title:string;summary:string;items:Array<{label:string;detail:string;status?:string;prompt?:string}>};
type PendingAction={type:'CREATE_DRAFT_TRIP';title:string;summary:string;details:Array<{label:string;value:string}>;confirmationToken:string;idempotencyKey:string;expiresAt:string;state?:'pending'|'confirming'|'confirmed'|'failed'};
type WorkflowHandoff={type:'OPEN_MAINTENANCE_FORM'|'OPEN_FUEL_FORM';label:string;summary:string;payload:{vehicleId:string;vehicleName:string;liters?:number;cost?:number;odometerKm?:number}};
type ChatMessage={id:string;role:'user'|'assistant';content:string;createdAt:string;evidence?:Evidence[];actions?:PendingAction[];handoffs?:WorkflowHandoff[];failed?:boolean};
type ChatResponse={message:string;evidence:Evidence[];actions?:PendingAction[];handoffs?:WorkflowHandoff[];asOf:string};
type ChatStatus={configured:boolean;model:string;readOnly:boolean;guardedActions:string[];tools:string[]};

const promptsByPage:Record<string,string[]>={
  dashboard:['Help me assign this unassigned trip.','Build a weekly operations report.','Explain why fleet utilization decreased.'],
  vehicles:['Which vehicles are available?','Show vehicles currently in the workshop.','Which vehicle has the highest odometer?'],
  drivers:['Show licence renewals required this month.','Show available drivers.','Which drivers are currently on trips?'],
  trips:['Help me assign this unassigned trip.','Find a replacement driver for this trip.','Which vehicle can safely carry 4,000 kg?'],
  maintenance:['Prepare maintenance for vehicles due for service.','What maintenance jobs are active?','Summarise maintenance costs.'],
  finance:['Prepare a fuel entry for a vehicle.','Build a weekly operations report.','Summarise operating spend for the last 30 days.'],
  analytics:['Explain current fleet performance.','What is our recorded operational cost?','How is vehicle ROI calculated here?']
};

function id(){return `${Date.now()}-${Math.random().toString(36).slice(2)}`}
function time(value:string){return new Intl.DateTimeFormat('en-IN',{hour:'2-digit',minute:'2-digit'}).format(new Date(value))}

type TripDetails={source:string;destination:string;cargoWeightKg:number;plannedDistanceKm:number;revenue:number};
type SelectedDraft=TripDetails&{vehicleId:string;driverId:string};
type SelectedResources={vehicleId:string;driverId:string;vehicleName:string;driverName:string};
type TripDetailKey=keyof TripDetails;
type TripFlow=SelectedResources&{details:Partial<TripDetails>};
const detailOrder:TripDetailKey[]=['source','destination','cargoWeightKg','plannedDistanceKm','revenue'];
const detailQuestions:Record<TripDetailKey,string>={source:'What is the trip origin?',destination:'What is the destination?',cargoWeightKg:'What is the cargo weight in kg?',plannedDistanceKm:'What is the planned distance in km?',revenue:'What is the expected revenue in ₹?'};
function numberFromAnswer(value:string){const match=value.replaceAll(',','').match(/-?\d+(?:\.\d+)?/);return match?Number(match[0]):Number.NaN}
function missingDetail(details:Partial<TripDetails>){return detailOrder.find(key=>details[key]===undefined)}
function detailsFromRequest(value:string):Partial<TripDetails>{const details:Partial<TripDetails>={},route=value.match(/\bfrom\s+(.+?)\s+to\s+(.+?)(?=[,.]|\s+(?:using|with|carrying|cargo|for)\b|$)/i),cargo=value.match(/([\d,.]+)\s*kg\b/i),distance=value.match(/([\d,.]+)\s*km\b/i),revenue=value.match(/(?:expected\s+)?revenue(?:\s+is|\s+of|\s*[:=])?\s*₹?\s*([\d,.]+)|₹\s*([\d,.]+)/i);if(route){details.source=route[1].trim();details.destination=route[2].trim()}if(cargo)details.cargoWeightKg=numberFromAnswer(cargo[1]);if(distance)details.plannedDistanceKm=numberFromAnswer(distance[1]);if(revenue)details.revenue=numberFromAnswer(revenue[1]||revenue[2]);return details}
function isGuidedWorkflow(value:string){return /\b(help\s+me\s+assign|assignment\s+options?|replacement\s+driver|prepare\s+maintenance|due\s+for\s+service|licen[cs]e\s+(?:renewal|expir)|weekly\s+(?:operations?\s+)?report|utili[sz]ation|prepare\s+(?:a\s+)?fuel\s+entry)\b/i.test(value)||/\b(?:carry|cargo)\b[^.?!]*\d[\d,.]*\s*kg\b/i.test(value)}

function AdminTripPlanner({busy,onCancel,onSelect}:{busy:boolean;onCancel:()=>void;onSelect:(resources:SelectedResources)=>void}){
  const [vehicles,setVehicles]=useState<Vehicle[]>([]),[drivers,setDrivers]=useState<Driver[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const [vehicleId,setVehicleId]=useState(''),[driverId,setDriverId]=useState('');
  const vehicle=vehicles.find(item=>item.id===vehicleId);const compatibleDrivers=drivers.filter(driver=>!vehicle||driver.licenseCategory===vehicle.requiredLicenseCategory);
  useEffect(()=>{let active=true;Promise.all([api<Vehicle[]>('/vehicles/available'),api<Driver[]>('/drivers/available')]).then(([nextVehicles,nextDrivers])=>{if(active){setVehicles(nextVehicles);setDrivers(nextDrivers)}}).catch(reason=>{if(active)setError((reason as Error).message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
  useEffect(()=>{if(driverId&&!compatibleDrivers.some(driver=>driver.id===driverId))setDriverId('')},[compatibleDrivers,driverId]);
  function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const driver=drivers.find(item=>item.id===driverId);if(!vehicle||!driver)return;onSelect({vehicleId,driverId,vehicleName:vehicle.name,driverName:driver.name})}
  return <section className="copilot-trip-planner" aria-labelledby="copilot-trip-planner-title"><header><ClipboardPlus/><div><b id="copilot-trip-planner-title">Choose trip resources</b><span>Select a live available vehicle and compatible driver.</span></div></header>{loading?<div className="copilot-planner-state"><LoaderCircle/> Loading available vehicles and drivers…</div>:error?<div className="copilot-planner-state error"><AlertTriangle/> {error}</div>:<form onSubmit={submit}><fieldset className="wide"><legend><Truck/> Choose an available vehicle</legend><div className="copilot-choice-list">{vehicles.map(item=><button type="button" className={vehicleId===item.id?'selected':''} aria-pressed={vehicleId===item.id} onClick={()=>setVehicleId(item.id)} key={item.id}><span><b>{item.name}</b><small>{item.registrationNo} · {item.type}</small></span><strong>{item.capacityKg.toLocaleString('en-IN')} kg</strong>{vehicleId===item.id&&<Check/>}</button>)}{!vehicles.length&&<p>No available vehicles were found.</p>}</div></fieldset><fieldset className="wide" disabled={!vehicleId}><legend><UserRound/> Choose a compatible driver</legend><div className="copilot-choice-list">{compatibleDrivers.map(item=><button type="button" className={driverId===item.id?'selected':''} aria-pressed={driverId===item.id} onClick={()=>setDriverId(item.id)} key={item.id}><span><b>{item.name}</b><small>{item.licenseCategory} licence · expires {new Date(item.licenseExpiry).toLocaleDateString('en-IN')}</small></span><strong>Safety {item.safetyScore}</strong>{driverId===item.id&&<Check/>}</button>)}{vehicleId&&!compatibleDrivers.length&&<p>No compatible available drivers were found.</p>}{!vehicleId&&<p>Choose a vehicle to see compatible drivers.</p>}</div></fieldset><div className="copilot-planner-actions"><button type="button" onClick={onCancel}>Cancel</button><button type="submit" disabled={busy||!vehicleId||!driverId}>Continue in chat</button></div></form>}</section>
}

export function ChatDrawer({open,onClose,user,page,onTripCreated}:{open:boolean;onClose:()=>void;user:User;page:string;onTripCreated?:()=>void}){
  const storageKey=`fleetpilot_copilot_${user.organizationId}_${user.id}_${user.role}`;const legacyStorageKey=`fleetpilot_copilot_${user.organizationId}_${user.id}`;
  const [messages,setMessages]=useState<ChatMessage[]>(()=>{try{return JSON.parse(sessionStorage.getItem(storageKey)||'[]')}catch{return[]}});
  const [value,setValue]=useState(''),[busy,setBusy]=useState(false),[busyAction,setBusyAction]=useState(''),[plannerOpen,setPlannerOpen]=useState(false),[tripFlow,setTripFlow]=useState<TripFlow|null>(null),[initialDetails,setInitialDetails]=useState<Partial<TripDetails>>({}),[status,setStatus]=useState<ChatStatus|null>(null),[statusError,setStatusError]=useState('');
  const endRef=useRef<HTMLDivElement>(null),inputRef=useRef<HTMLTextAreaElement>(null),closeRef=useRef<HTMLButtonElement>(null);
  const starters=useMemo(()=>promptsByPage[page]||promptsByPage.dashboard,[page]);
  const canCreateTrip=status?.guardedActions.includes('CREATE_DRAFT_TRIP')===true;

  useEffect(()=>{api<ChatStatus>('/chat/status').then(setStatus).catch(error=>setStatusError((error as Error).message))},[]);
  useEffect(()=>{localStorage.removeItem(legacyStorageKey)},[legacyStorageKey]);
  useEffect(()=>{const safe=messages.slice(-30).map(({handoffs:_handoffs,...message})=>({...message,actions:message.actions?.map(action=>({...action,confirmationToken:''}))}));sessionStorage.setItem(storageKey,JSON.stringify(safe))},[messages,storageKey]);
  useEffect(()=>{if(open){closeRef.current?.focus();setTimeout(()=>endRef.current?.scrollIntoView({block:'end'}),0)}},[open]);
  useEffect(()=>{endRef.current?.scrollIntoView({behavior:'smooth',block:'end'})},[messages,busy]);
  useEffect(()=>{if(!open)return;const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose()};document.addEventListener('keydown',onKey);return()=>document.removeEventListener('keydown',onKey)},[open,onClose]);

  async function send(content:string){
    const cleaned=content.trim();if(!cleaned||busy)return;
    if(tripFlow){const userMessage:ChatMessage={id:id(),role:'user',content:cleaned,createdAt:new Date().toISOString()};setMessages(current=>[...current,userMessage]);setValue('');if(/^cancel\b/i.test(cleaned)){setTripFlow(null);setMessages(current=>[...current,{id:id(),role:'assistant',content:'Trip preparation cancelled. No record was created.',createdAt:new Date().toISOString()}]);return}const key=missingDetail(tripFlow.details);if(!key)return;const numeric=!['source','destination'].includes(key),numericValue=numberFromAnswer(cleaned),detailValue=numeric?numericValue:cleaned,valueIsValid=numeric?Number.isFinite(numericValue)&&(key==='revenue'?numericValue>=0:numericValue>0):cleaned.length>=2;if(!valueIsValid){setMessages(current=>[...current,{id:id(),role:'assistant',content:`I could not read a valid ${key==='revenue'?'revenue amount':key==='cargoWeightKg'?'cargo weight':key==='plannedDistanceKm'?'distance':key}. ${detailQuestions[key]}`,createdAt:new Date().toISOString()}]);return}const details={...tripFlow.details,[key]:detailValue},next=missingDetail(details);if(next){setTripFlow({...tripFlow,details});setMessages(current=>[...current,{id:id(),role:'assistant',content:detailQuestions[next],createdAt:new Date().toISOString()}]);return}setTripFlow(null);await prepareSelectedTrip({...details as TripDetails,vehicleId:tripFlow.vehicleId,driverId:tripFlow.driverId});return}
    const tripActionIntent=/\b(create|draft|plan|prepare|confirm)\b[^.?!]*\btrip\b|\btrip\b[^.?!]*\b(create|draft|plan|prepare|confirm)\b/i.test(cleaned);if(status?.configured===false&&!(canCreateTrip&&tripActionIntent)&&!isGuidedWorkflow(cleaned))return;
    const userMessage:ChatMessage={id:id(),role:'user',content:cleaned,createdAt:new Date().toISOString()};const prior=messages.slice(-12);setMessages(current=>[...current,userMessage]);setValue('');setBusy(true);
    const pendingAction=messages.some(message=>message.actions?.some(action=>Boolean(action.confirmationToken)&&action.state!=='confirmed'));
    if(canCreateTrip&&tripActionIntent){setPlannerOpen(!pendingAction);if(!pendingAction)setInitialDetails(detailsFromRequest(cleaned));setMessages(current=>[...current,{id:id(),role:'assistant',content:pendingAction?'Your secure trip proposal is already prepared. Use the “Confirm and create draft” button on the proposal card above; typed confirmation cannot execute a write.':'Choose an available vehicle and compatible driver below. After your selection, I will ask only for the trip details that are still missing.',createdAt:new Date().toISOString()}]);setBusy(false);return}
    try{const response=await api<ChatResponse>('/chat',{method:'POST',body:JSON.stringify({message:cleaned,history:prior.map(message=>({role:message.role,content:message.content})),context:{page}})});setMessages(current=>[...current,{id:id(),role:'assistant',content:response.message,createdAt:response.asOf,evidence:response.evidence,actions:response.actions,handoffs:response.handoffs}])}
    catch(error){setMessages(current=>[...current,{id:id(),role:'assistant',content:(error as Error).message,createdAt:new Date().toISOString(),failed:true}])}
    finally{setBusy(false);setTimeout(()=>inputRef.current?.focus(),0)}
  }
  function submit(event:FormEvent){event.preventDefault();void send(value)}
  function clear(){setMessages([]);setPlannerOpen(false);setTripFlow(null);setInitialDetails({});sessionStorage.removeItem(storageKey);inputRef.current?.focus()}
  async function prepareSelectedTrip(draft:SelectedDraft){if(busy)return;setPlannerOpen(false);setBusy(true);try{const response=await api<ChatResponse>('/chat/actions/prepare',{method:'POST',body:JSON.stringify(draft)});setMessages(current=>[...current,{id:id(),role:'assistant',content:response.message,createdAt:new Date().toISOString(),evidence:response.evidence,actions:response.actions}]);if(!response.actions?.length){setInitialDetails({source:draft.source,destination:draft.destination,cargoWeightKg:draft.cargoWeightKg,plannedDistanceKm:draft.plannedDistanceKm,revenue:draft.revenue});setPlannerOpen(true)}}catch(error){setMessages(current=>[...current,{id:id(),role:'assistant',content:(error as Error).message,createdAt:new Date().toISOString(),failed:true}])}finally{setBusy(false)}}
  function selectResources(resources:SelectedResources){setPlannerOpen(false);setMessages(current=>[...current,{id:id(),role:'user',content:`Selected ${resources.vehicleName} with ${resources.driverName}.`,createdAt:new Date().toISOString()}]);const details=initialDetails,next=missingDetail(details);setInitialDetails({});if(next){setTripFlow({...resources,details});setMessages(current=>[...current,{id:id(),role:'assistant',content:detailQuestions[next],createdAt:new Date().toISOString()}])}else void prepareSelectedTrip({...details as TripDetails,vehicleId:resources.vehicleId,driverId:resources.driverId})}
  function openHandoff(handoff:WorkflowHandoff){window.dispatchEvent(new CustomEvent('fleetpilot:workflow-handoff',{detail:handoff}));onClose()}
  async function confirmAction(messageId:string,index:number){const message=messages.find(item=>item.id===messageId),action=message?.actions?.[index];if(!action?.confirmationToken||busyAction)return;const key=`${messageId}-${index}`;setBusyAction(key);setMessages(current=>current.map(item=>item.id===messageId?{...item,actions:item.actions?.map((entry,entryIndex)=>entryIndex===index?{...entry,state:'confirming' as const}:entry)}:item));try{const result=await api<{message:string;trip:{tripNo:string;source:string;destination:string}}>('/chat/actions/confirm',{method:'POST',body:JSON.stringify({confirmationToken:action.confirmationToken,idempotencyKey:action.idempotencyKey})});setMessages(current=>[...current.map(item=>item.id===messageId?{...item,actions:item.actions?.map((entry,entryIndex)=>entryIndex===index?{...entry,state:'confirmed' as const,confirmationToken:''}:entry)}:item),{id:id(),role:'assistant',content:result.message,createdAt:new Date().toISOString(),evidence:[{tool:'confirmed_action',title:'Draft created',summary:result.trip.tripNo,items:[{label:`${result.trip.source} → ${result.trip.destination}`,detail:'Saved as a draft. Vehicle and driver remain available until dispatch.',status:'DRAFT'}]}]}]);onTripCreated?.()}catch(error){setMessages(current=>[...current.map(item=>item.id===messageId?{...item,actions:item.actions?.map((entry,entryIndex)=>entryIndex===index?{...entry,state:'failed' as const}:entry)}:item),{id:id(),role:'assistant',content:(error as Error).message,createdAt:new Date().toISOString(),failed:true}])}finally{setBusyAction('')}}
  if(!open)return null;
  const unavailable=status?.configured===false,guarded=canCreateTrip;
  return <div className="copilot-layer" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><aside className="copilot" role="dialog" aria-modal="true" aria-labelledby="copilot-title">
    <header className="copilot-head"><div className="copilot-mark"><Sparkles/></div><div><span>Role-aware operations assistant</span><h2 id="copilot-title">FleetPilot Copilot</h2></div><div className="copilot-head-actions"><button onClick={clear} title="Clear conversation" aria-label="Clear conversation"><Eraser/></button><button ref={closeRef} onClick={onClose} title="Close Copilot" aria-label="Close Copilot"><X/></button></div></header>
    <div className="copilot-scope"><ShieldCheck/><span><b>{roleLabel[user.role]}</b> · {guarded?'Data stays role-scoped; writes require confirmation.':'Answers stay within this role’s read access.'}</span><i>{guarded?'GUARDED':'READ ONLY'}</i></div>
    {guarded&&<div className="copilot-admin-actions"><button onClick={()=>{if(plannerOpen)setPlannerOpen(false);else{setInitialDetails({});setTripFlow(null);setPlannerOpen(true)}}} disabled={busy}><ClipboardPlus/>{plannerOpen?'Close trip planner':'Create trip with Copilot'}</button><small>Owner / Administrator only</small></div>}
    <div className="copilot-messages" aria-live="polite">
      {statusError&&<div className="copilot-config"><AlertTriangle/><div><b>Copilot status unavailable</b><p>{statusError}</p></div></div>}
      {unavailable&&<div className="copilot-config"><AlertTriangle/><div><b>Backend setup required</b><p>Add <code>GROQ_API_KEY</code> to <code>backend/.env</code>, then restart the API. The key stays on the server.</p></div></div>}
      {!messages.length&&!statusError&&!unavailable&&<div className="copilot-welcome"><span><MessageSquareText/></span><h3>Plan with current fleet data.</h3><p>{guarded?'I can identify risks, recommend eligible assignments, and prepare a draft trip for your explicit confirmation. Live dispatch and other writes remain unavailable.':'I can answer using the current fleet data available to your role. I cannot change operational records.'}</p><div className="copilot-starters">{starters.map(prompt=><button key={prompt} onClick={()=>void send(prompt)}>{prompt}</button>)}</div></div>}
      {messages.map(message=><article key={message.id} className={`copilot-message ${message.role}${message.failed?' failed':''}`}><div className="copilot-bubble">{message.failed&&<AlertTriangle/>}<p>{message.content}</p></div>{message.evidence?.map((source,index)=><section className="evidence-card" key={`${source.tool}-${index}`}><header><Database/><div><b>{source.title}</b><span>{source.summary}</span></div></header>{source.items.length>0&&<div className="evidence-items">{source.items.slice(0,5).map((item,itemIndex)=><div key={`${item.label}-${itemIndex}`}><span><b>{item.label}</b><small>{item.detail}</small></span>{item.status&&<i className={`evidence-status s-${item.status.toLowerCase()}`}>{item.status.replaceAll('_',' ')}</i>}{item.prompt&&<button className="evidence-followup" onClick={()=>void send(item.prompt!)}>Select</button>}</div>)}</div>}</section>)}{message.actions?.map((action,index)=>{const actionKey=`${message.id}-${index}`,expired=new Date(action.expiresAt).getTime()<Date.now()||!action.confirmationToken,confirmed=action.state==='confirmed';return <section className={`copilot-action-card ${confirmed?'confirmed':''}`} key={action.idempotencyKey}><header>{confirmed?<Check/>:<ShieldCheck/>}<div><b>{action.title}</b><span>{action.summary}</span></div></header><dl>{action.details.map(detail=><div key={detail.label}><dt>{detail.label}</dt><dd>{detail.value}</dd></div>)}</dl><button disabled={expired||confirmed||busyAction===actionKey} onClick={()=>void confirmAction(message.id,index)}>{confirmed?'Draft created':expired?'Proposal expired':busyAction===actionKey?'Revalidating…':'Confirm and create draft'}</button><small>{confirmed?'The confirmed result is recorded in FleetPilot.':'FleetPilot will recheck permissions and assignment availability before saving.'}</small></section>})}{message.handoffs?.map(handoff=><section className="copilot-handoff-card" key={`${handoff.type}-${handoff.payload.vehicleId}`}><ClipboardPlus/><div><b>{handoff.label}</b><span>{handoff.summary}</span></div><button onClick={()=>openHandoff(handoff)}>Open form</button></section>)}<time>{time(message.createdAt)}</time></article>)}
      {plannerOpen&&guarded&&<AdminTripPlanner busy={busy} onCancel={()=>{setPlannerOpen(false);setInitialDetails({})}} onSelect={selectResources}/>}
      {busy&&<div className="copilot-thinking"><LoaderCircle/><span>Checking FleetPilot records…</span></div>}<div ref={endRef}/>
    </div>
    <form className="copilot-compose" onSubmit={submit}><textarea ref={inputRef} aria-label="Ask FleetPilot Copilot" placeholder={tripFlow?'Reply with the requested trip detail…':unavailable?'Configure the backend to start chatting':'Ask about vehicles, drivers, trips or costs…'} value={value} disabled={busy||(unavailable&&!tripFlow)} rows={2} onChange={event=>setValue(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();event.currentTarget.form?.requestSubmit()}}}/><button type="submit" disabled={!value.trim()||busy||(unavailable&&!tripFlow)} aria-label="Send message"><ArrowUp/></button><small>{tripFlow?'Reply “cancel” to stop. No trip is created until the final confirmation button is clicked.':'Fleet data may change after an answer. Verify critical decisions in the relevant module.'}</small></form>
  </aside></div>
}
