import { useCallback, useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react';
import { Activity, BarChart3, Bell, BusFront, CalendarDays, Check, ChevronDown, CircleDollarSign, Download, Fuel, Gauge, LayoutDashboard, LogOut, Menu, Plus, Route, Search, Settings, ShieldCheck, Truck, UserRound, UsersRound, Wrench, X } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis } from 'recharts';
import { api, API_URL, hasSession, roleLabel, setToken, type Role, type User } from './api';
import type { Driver, Finance, Maintenance, Trip, Vehicle } from './types';

const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
const pretty=(s:string)=>s.toLowerCase().replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const date=(s:string)=>new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(s));
const roles:Role[]=['FLEET_MANAGER','DISPATCHER','SAFETY_OFFICER','FINANCIAL_ANALYST'];

function Logo({light=false}:{light?:boolean}){return <div className={`logo ${light?'light':''}`}><span><Route size={21}/></span><div>Transit<span>Ops</span><small>Smart transport operations</small></div></div>}
function Button({children,variant='primary',...props}:{children:ReactNode;variant?:'primary'|'ghost'|'danger';[key:string]:any}){return <button className={`button ${variant}`} {...props}>{children}</button>}
function Status({value}:{value:string}){return <span className={`status s-${value.toLowerCase()}`}><i/>{pretty(value)}</span>}
function Empty({text='No records found'}:{text?:string}){return <div className="empty"><Search size={28}/><p>{text}</p></div>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal"><div className="modal-head"><div><small>TransitOps</small><h2>{title}</h2></div><button className="icon-btn" onClick={onClose}><X/></button></div>{children}</div></div>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function PageTitle({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action?:ReactNode}){return <div className="page-title"><div><span>{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action}</div>}

function Login({onLogin}:{onLogin:(u:User)=>void}){
  const [form,setForm]=useState({email:'dispatcher@transitops.in',password:'Password@123',role:'DISPATCHER' as Role}); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const out=await api<{token:string;user:User}>('/auth/login',{method:'POST',body:JSON.stringify(form)});setToken(out.token);onLogin(out.user)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  function changeRole(role:Role){const mail:Record<Role,string>={FLEET_MANAGER:'manager@transitops.in',DISPATCHER:'dispatcher@transitops.in',SAFETY_OFFICER:'safety@transitops.in',FINANCIAL_ANALYST:'finance@transitops.in'};setForm(f=>({...f,role,email:mail[role]}))}
  return <main className="login-page"><section className="login-visual"><Logo light/><div className="login-copy"><span className="eyebrow">One platform. Total control.</span><h1>Move every operation<br/>forward.</h1><p>Vehicles, people, trips and spend—connected in one intelligent transport command center.</p><div className="mini-stats"><div><b>99.9%</b><span>Platform uptime</span></div><div><b>24/7</b><span>Fleet visibility</span></div></div></div><div className="road-lines"/><footer>TRANSITOPS © 2026 · OPERATIONS, SIMPLIFIED.</footer></section><section className="login-panel"><div className="login-box"><div className="mobile-logo"><Logo/></div><span className="eyebrow">Welcome back</span><h2>Sign in to TransitOps</h2><p>Use your operations account to continue.</p>{error&&<div className="alert"><X size={17}/><span><b>Unable to sign in</b>{error}</span></div>}<form onSubmit={submit}><Field label="Work email"><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></Field><Field label="Password"><input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/></Field><Field label="Access role"><select value={form.role} onChange={e=>changeRole(e.target.value as Role)}>{roles.map(r=><option key={r} value={r}>{roleLabel[r]}</option>)}</select></Field><div className="form-meta"><label><input type="checkbox" defaultChecked/> Keep me signed in</label><a>Forgot password?</a></div><Button type="submit" disabled={busy}>{busy?'Signing in…':'Sign in securely'} <ShieldCheck size={18}/></Button></form><div className="demo-note"><Check size={16}/><span>Demo access is pre-filled. Password for all roles: <b>Password@123</b></span></div></div></section></main>
}

type Page='dashboard'|'vehicles'|'drivers'|'trips'|'maintenance'|'finance'|'analytics'|'settings';
const nav:Array<{id:Page;label:string;icon:any;roles?:Role[]}>= [
  {id:'dashboard',label:'Overview',icon:LayoutDashboard},{id:'vehicles',label:'Fleet registry',icon:Truck},{id:'drivers',label:'Drivers',icon:UsersRound},{id:'trips',label:'Trip dispatch',icon:Route,roles:['DISPATCHER','FLEET_MANAGER']},{id:'maintenance',label:'Maintenance',icon:Wrench,roles:['FLEET_MANAGER']},{id:'finance',label:'Fuel & expenses',icon:Fuel,roles:['FINANCIAL_ANALYST','FLEET_MANAGER']},{id:'analytics',label:'Reports',icon:BarChart3},{id:'settings',label:'Settings & RBAC',icon:Settings,roles:['FLEET_MANAGER']}
];
function Shell({user,onLogout}:{user:User;onLogout:()=>void}){
  const [page,setPage]=useState<Page>('dashboard');const [menu,setMenu]=useState(false);const [search,setSearch]=useState('');
  const visible=nav.filter(n=>!n.roles||n.roles.includes(user.role));
  return <div className="app"><aside className={menu?'open':''}><div className="aside-head"><Logo/><button onClick={()=>setMenu(false)}><X/></button></div><div className="workspace"><span>Workspace</span><b>TransitOps India</b><ChevronDown size={15}/></div><nav><span className="nav-label">OPERATIONS</span>{visible.slice(0,-1).map(n=><button key={n.id} className={page===n.id?'active':''} onClick={()=>{setPage(n.id);setMenu(false)}}><n.icon size={19}/>{n.label}</button>)}<span className="nav-label">ADMINISTRATION</span>{visible.slice(-1).map(n=><button key={n.id} className={page===n.id?'active':''} onClick={()=>{setPage(n.id);setMenu(false)}}><n.icon size={19}/>{n.label}</button>)}</nav><div className="user-card"><div className="avatar">{user.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div><b>{user.name}</b><span>{roleLabel[user.role]}</span></div><button onClick={onLogout} title="Sign out"><LogOut size={18}/></button></div></aside>{menu&&<div className="scrim" onClick={()=>setMenu(false)}/>}<section className="app-main"><header><button className="menu-btn" onClick={()=>setMenu(true)}><Menu/></button><div className="global-search"><Search/><input placeholder="Search vehicles, drivers or trips…" value={search} onChange={e=>setSearch(e.target.value)}/><kbd>⌘ K</kbd></div><div className="header-actions"><button className="icon-btn"><Bell/><i/></button><span className="date-chip"><CalendarDays size={16}/>{new Intl.DateTimeFormat('en-IN',{day:'numeric',month:'short'}).format(new Date())}</span><div className="role-chip"><span>{roleLabel[user.role]}</span></div></div></header><div className="content"><PageContent page={page} user={user} globalSearch={search}/></div></section></div>
}

function PageContent({page,user,globalSearch}:{page:Page;user:User;globalSearch:string}){
  if(page==='dashboard')return <Dashboard/>; if(page==='vehicles')return <Vehicles user={user} globalSearch={globalSearch}/>;if(page==='drivers')return <Drivers user={user} globalSearch={globalSearch}/>;if(page==='trips')return <Trips/>;if(page==='maintenance')return <MaintenancePage/>;if(page==='finance')return <FinancePage/>;if(page==='analytics')return <Analytics/>;return <SettingsPage user={user}/>;
}

function Dashboard(){
  const [data,setData]=useState<any>();useEffect(()=>{api('/dashboard').then(setData)},[]);if(!data)return <Loading/>;
  const cards=[['Active vehicles',data.kpis.activeVehicles,BusFront,'blue'],['Available now',data.kpis.availableVehicles,Check,'green'],['In maintenance',data.kpis.inMaintenance,Wrench,'orange'],['Active trips',data.kpis.activeTrips,Route,'purple'],['Drivers on duty',data.kpis.driversOnDuty,UsersRound,'cyan'],['Fleet utilization',`${data.kpis.fleetUtilization}%`,Gauge,'navy']];
  const statusData=Object.entries(data.vehicleStatus).map(([name,value])=>({name:pretty(name),value}));
  return <><PageTitle eyebrow="Operations center" title="Good evening, Raven" description="Here’s what’s happening across your transport network today." action={<Button><Plus size={17}/> New trip</Button>}/><div className="notice"><span><Activity size={18}/></span><div><b>All systems operational</b><p>Fleet data last synchronized just now</p></div><i/></div><div className="kpi-grid">{cards.map(([label,value,Icon,color]:any)=><div className="kpi" key={label}><div className={`kpi-icon ${color}`}><Icon/></div><div><span>{label}</span><strong>{value}</strong><small>Live fleet status</small></div></div>)}</div><div className="dashboard-grid"><section className="panel wide"><div className="panel-head"><div><span>Live operations</span><h3>Recent trips</h3></div><button>View all <span>→</span></button></div><div className="table-wrap"><table><thead><tr><th>Trip</th><th>Route</th><th>Vehicle</th><th>Driver</th><th>Status</th></tr></thead><tbody>{data.recentTrips.map((t:Trip)=><tr key={t.id}><td><b>{t.tripNo}</b></td><td>{t.source} <span className="route-arrow">→</span> {t.destination}</td><td>{t.vehicle.name}</td><td>{t.driver.name}</td><td><Status value={t.status}/></td></tr>)}</tbody></table></div></section><section className="panel"><div className="panel-head"><div><span>Distribution</span><h3>Vehicle status</h3></div></div><div className="donut-wrap"><div className="donut" style={{'--percent':`${data.kpis.fleetUtilization}%`} as any}><b>{data.kpis.activeVehicles}</b><span>Total fleet</span></div><div className="legend">{statusData.map((x:any,i)=><div key={x.name}><i className={`dot d${i}`}/><span>{x.name}</span><b>{x.value as number}</b></div>)}</div></div></section></div></>
}
function Loading(){return <div className="loading"><span/><p>Loading operations…</p></div>}

function Toolbar({search,setSearch,children}:{search:string;setSearch:(s:string)=>void;children?:ReactNode}){return <div className="toolbar"><div className="search-box"><Search/><input placeholder="Search records…" value={search} onChange={e=>setSearch(e.target.value)}/></div>{children}</div>}
function Vehicles({user,globalSearch}:{user:User;globalSearch:string}){
  const [rows,setRows]=useState<Vehicle[]>([]),[search,setSearch]=useState(globalSearch),[status,setStatus]=useState(''),[edit,setEdit]=useState<Vehicle|Partial<Vehicle>|null>(null);const can=user.role==='FLEET_MANAGER';
  const load=useCallback(()=>api<Vehicle[]>(`/vehicles?q=${encodeURIComponent(search)}${status?`&status=${status}`:''}`).then(setRows),[search,status]);useEffect(()=>{const t=setTimeout(load,200);return()=>clearTimeout(t)},[load]);useEffect(()=>setSearch(globalSearch),[globalSearch]);
  async function remove(v:Vehicle){if(confirm(`Delete ${v.name}?`)){await api(`/vehicles/${v.id}`,{method:'DELETE'});load()}}
  return <><PageTitle eyebrow="Fleet operations" title="Vehicle registry" description={`${rows.length} vehicles · central source of truth for your fleet`} action={can?<Button onClick={()=>setEdit({})}><Plus size={17}/> Add vehicle</Button>:undefined}/><Toolbar search={search} setSearch={setSearch}><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{['AVAILABLE','ON_TRIP','IN_SHOP','RETIRED'].map(x=><option key={x}>{x}</option>)}</select></Toolbar><section className="panel records"><div className="table-wrap"><table><thead><tr><th>Vehicle</th><th>Registration</th><th>Type</th><th>Capacity</th><th>Odometer</th><th>Acquisition</th><th>Status</th>{can&&<th/>}</tr></thead><tbody>{rows.map(v=><tr key={v.id}><td><div className="entity"><span><Truck/></span><div><b>{v.name}</b><small>{v.region} region</small></div></div></td><td><code>{v.registrationNo}</code></td><td>{v.type}</td><td>{v.capacityKg.toLocaleString()} kg</td><td>{v.odometerKm.toLocaleString()} km</td><td>{money(v.acquisitionCost)}</td><td><Status value={v.status}/></td>{can&&<td className="actions"><button onClick={()=>setEdit(v)}>Edit</button><button onClick={()=>remove(v)}>Delete</button></td>}</tr>)}</tbody></table>{!rows.length&&<Empty/>}</div></section>{edit&&<VehicleForm value={edit} onClose={()=>setEdit(null)} onSaved={()=>{setEdit(null);load()}}/>}</>
}
function VehicleForm({value,onClose,onSaved}:{value:Partial<Vehicle>;onClose:()=>void;onSaved:()=>void}){const [error,setError]=useState('');async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));try{await api(value.id?`/vehicles/${value.id}`:'/vehicles',{method:value.id?'PUT':'POST',body:JSON.stringify(f)});onSaved()}catch(e){setError((e as Error).message)}}return <Modal title={value.id?'Edit vehicle':'Register a vehicle'} onClose={onClose}><form className="modal-form" onSubmit={save}>{error&&<div className="alert"><X/>{error}</div>}<div className="form-grid"><Field label="Registration number"><input name="registrationNo" defaultValue={value.registrationNo} required/></Field><Field label="Vehicle name / model"><input name="name" defaultValue={value.name} required/></Field><Field label="Type"><select name="type" defaultValue={value.type||'Van'}><option>Van</option><option>Truck</option><option>Mini Truck</option><option>Bus</option></select></Field><Field label="Region"><select name="region" defaultValue={value.region||'West'}><option>West</option><option>North</option><option>South</option><option>East</option><option>Central</option></select></Field><Field label="Maximum capacity (kg)"><input name="capacityKg" type="number" min="1" defaultValue={value.capacityKg||500} required/></Field><Field label="Odometer (km)"><input name="odometerKm" type="number" min="0" defaultValue={value.odometerKm||0} required/></Field><Field label="Acquisition cost (₹)"><input name="acquisitionCost" type="number" min="0" defaultValue={value.acquisitionCost||0} required/></Field><Field label="Status"><select name="status" defaultValue={value.status||'AVAILABLE'}>{['AVAILABLE','ON_TRIP','IN_SHOP','RETIRED'].map(x=><option key={x}>{x}</option>)}</select></Field></div><div className="modal-actions"><Button type="button" variant="ghost" onClick={onClose}>Cancel</Button><Button type="submit">{value.id?'Save changes':'Register vehicle'}</Button></div></form></Modal>}

function Drivers({user,globalSearch}:{user:User;globalSearch:string}){
  const [rows,setRows]=useState<Driver[]>([]),[search,setSearch]=useState(globalSearch),[edit,setEdit]=useState<Driver|Partial<Driver>|null>(null);const can=['FLEET_MANAGER','SAFETY_OFFICER'].includes(user.role);const canDelete=user.role==='FLEET_MANAGER';const load=useCallback(()=>api<Driver[]>(`/drivers?q=${encodeURIComponent(search)}`).then(setRows),[search]);useEffect(()=>{const t=setTimeout(load,200);return()=>clearTimeout(t)},[load]);useEffect(()=>setSearch(globalSearch),[globalSearch]);async function remove(d:Driver){if(confirm(`Delete ${d.name}?`)){await api(`/drivers/${d.id}`,{method:'DELETE'});load()}}
  return <><PageTitle eyebrow="People & safety" title="Driver profiles" description="License compliance, safety scores and real-time availability" action={can?<Button onClick={()=>setEdit({})}><Plus size={17}/> Add driver</Button>:undefined}/><Toolbar search={search} setSearch={setSearch}/><section className="panel records"><div className="table-wrap"><table><thead><tr><th>Driver</th><th>License</th><th>Category</th><th>Expires</th><th>Safety score</th><th>Status</th>{can&&<th/>}</tr></thead><tbody>{rows.map(d=><tr key={d.id}><td><div className="entity"><span className="person"><UserRound/></span><div><b>{d.name}</b><small>{d.contact}</small></div></div></td><td><code>{d.licenseNo}</code></td><td>{d.licenseCategory}</td><td className={new Date(d.licenseExpiry)<new Date()?'expired':''}>{date(d.licenseExpiry)}</td><td><div className="score"><b>{d.safetyScore}</b><span><i style={{width:`${d.safetyScore}%`}}/></span></div></td><td><Status value={d.status}/></td>{can&&<td className="actions"><button onClick={()=>setEdit(d)}>Edit</button>{canDelete&&<button onClick={()=>remove(d)}>Delete</button>}</td>}</tr>)}</tbody></table>{!rows.length&&<Empty/>}</div></section>{edit&&<DriverForm value={edit} onClose={()=>setEdit(null)} onSaved={()=>{setEdit(null);load()}}/>}</>
}
function DriverForm({value,onClose,onSaved}:{value:Partial<Driver>;onClose:()=>void;onSaved:()=>void}){const [error,setError]=useState('');async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));try{await api(value.id?`/drivers/${value.id}`:'/drivers',{method:value.id?'PUT':'POST',body:JSON.stringify(f)});onSaved()}catch(e){setError((e as Error).message)}}return <Modal title={value.id?'Edit driver':'Create driver profile'} onClose={onClose}><form className="modal-form" onSubmit={save}>{error&&<div className="alert"><X/>{error}</div>}<div className="form-grid"><Field label="Full name"><input name="name" defaultValue={value.name} required/></Field><Field label="Contact number"><input name="contact" defaultValue={value.contact} required/></Field><Field label="License number"><input name="licenseNo" defaultValue={value.licenseNo} required/></Field><Field label="License category"><select name="licenseCategory" defaultValue={value.licenseCategory||'LMV'}><option>LMV</option><option>HMV</option><option>MCWG</option></select></Field><Field label="License expiry"><input name="licenseExpiry" type="date" defaultValue={value.licenseExpiry?.slice(0,10)} required/></Field><Field label="Safety score"><input name="safetyScore" type="number" min="0" max="100" defaultValue={value.safetyScore||100} required/></Field><Field label="Status"><select name="status" defaultValue={value.status||'AVAILABLE'}>{['AVAILABLE','ON_TRIP','OFF_DUTY','SUSPENDED'].map(x=><option key={x}>{x}</option>)}</select></Field></div><div className="modal-actions"><Button type="button" variant="ghost" onClick={onClose}>Cancel</Button><Button type="submit">Save profile</Button></div></form></Modal>}

function Trips(){const [rows,setRows]=useState<Trip[]>([]),[open,setOpen]=useState(false),[complete,setComplete]=useState<Trip|null>(null);const load=()=>api<Trip[]>('/trips').then(setRows);useEffect(()=>{load()},[]);async function action(id:string,type:'dispatch'|'cancel'){try{await api(`/trips/${id}/${type}`,{method:'POST'});load()}catch(e){alert((e as Error).message)}}return <><PageTitle eyebrow="Dispatch center" title="Trip operations" description="Plan, validate and monitor every shipment from depot to delivery" action={<Button onClick={()=>setOpen(true)}><Plus size={17}/> Create trip</Button>}/><div className="stage-strip"><div className="active"><i/><span>01</span><b>Draft</b></div><em/><div><i/><span>02</span><b>Dispatched</b></div><em/><div><i/><span>03</span><b>Completed</b></div></div><section className="panel records"><div className="table-wrap"><table><thead><tr><th>Trip</th><th>Route</th><th>Assignment</th><th>Cargo</th><th>Distance</th><th>Status</th><th/></tr></thead><tbody>{rows.map(t=><tr key={t.id}><td><b>{t.tripNo}</b><small>{date(t.createdAt)}</small></td><td><div className="route-cell"><span>{t.source}</span><i>→</i><span>{t.destination}</span></div></td><td><div><b>{t.vehicle.name}</b><small>{t.driver.name}</small></div></td><td>{t.cargoWeightKg.toLocaleString()} kg</td><td>{t.plannedDistanceKm} km</td><td><Status value={t.status}/></td><td className="actions">{t.status==='DRAFT'&&<><button onClick={()=>action(t.id,'dispatch')}>Dispatch</button><button onClick={()=>action(t.id,'cancel')}>Cancel</button></>}{t.status==='DISPATCHED'&&<><button onClick={()=>setComplete(t)}>Complete</button><button onClick={()=>action(t.id,'cancel')}>Cancel</button></>}</td></tr>)}</tbody></table>{!rows.length&&<Empty/>}</div></section>{open&&<TripForm onClose={()=>setOpen(false)} onSaved={()=>{setOpen(false);load()}}/>}{complete&&<CompleteTrip trip={complete} onClose={()=>setComplete(null)} onSaved={()=>{setComplete(null);load()}}/>}</>}
function TripForm({onClose,onSaved}:{onClose:()=>void;onSaved:()=>void}){const [vehicles,setVehicles]=useState<Vehicle[]>([]),[drivers,setDrivers]=useState<Driver[]>([]),[error,setError]=useState('');useEffect(()=>{Promise.all([api<Vehicle[]>('/vehicles/available'),api<Driver[]>('/drivers/available')]).then(([v,d])=>{setVehicles(v);setDrivers(d)})},[]);async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();try{await api('/trips',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});onSaved()}catch(e){setError((e as Error).message)}}return <Modal title="Plan a new trip" onClose={onClose}><form className="modal-form" onSubmit={save}>{error&&<div className="alert"><X/>{error}</div>}<div className="form-grid"><Field label="Source"><input name="source" placeholder="Ahmedabad Depot" required/></Field><Field label="Destination"><input name="destination" placeholder="Surat Warehouse" required/></Field><Field label="Available vehicle"><select name="vehicleId" required><option value="">Select vehicle</option>{vehicles.map(v=><option value={v.id} key={v.id}>{v.name} · {v.capacityKg} kg</option>)}</select></Field><Field label="Available driver"><select name="driverId" required><option value="">Select driver</option>{drivers.map(d=><option value={d.id} key={d.id}>{d.name} · Score {d.safetyScore}</option>)}</select></Field><Field label="Cargo weight (kg)"><input name="cargoWeightKg" type="number" min="1" required/></Field><Field label="Planned distance (km)"><input name="plannedDistanceKm" type="number" min="1" required/></Field><Field label="Expected revenue (₹)"><input name="revenue" type="number" min="0" defaultValue="0"/></Field></div><div className="rule-note"><ShieldCheck/><span>Capacity, availability and license eligibility will be validated before creation.</span></div><div className="modal-actions"><Button type="button" variant="ghost" onClick={onClose}>Cancel</Button><Button type="submit">Create draft</Button></div></form></Modal>}
function CompleteTrip({trip,onClose,onSaved}:{trip:Trip;onClose:()=>void;onSaved:()=>void}){async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();try{await api(`/trips/${trip.id}/complete`,{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});onSaved()}catch(e){alert((e as Error).message)}}return <Modal title={`Complete ${trip.tripNo}`} onClose={onClose}><form className="modal-form" onSubmit={save}><p className="modal-copy">Enter the closing readings. Vehicle and driver will become available automatically.</p><div className="form-grid"><Field label="Final odometer (km)"><input name="finalOdometerKm" type="number" min={trip.vehicle.odometerKm} defaultValue={trip.vehicle.odometerKm+trip.plannedDistanceKm} required/></Field><Field label="Fuel consumed (liters)"><input name="fuelConsumedL" type="number" min="0.1" step="0.1" required/></Field></div><div className="modal-actions"><Button type="button" variant="ghost" onClick={onClose}>Cancel</Button><Button type="submit">Complete trip</Button></div></form></Modal>}

function MaintenancePage(){const [rows,setRows]=useState<Maintenance[]>([]),[open,setOpen]=useState(false);const load=()=>api<Maintenance[]>('/maintenance').then(setRows);useEffect(()=>{load()},[]);async function close(id:string){await api(`/maintenance/${id}/close`,{method:'POST'});load()}return <><PageTitle eyebrow="Fleet health" title="Maintenance control" description="Service history, active workshop jobs and vehicle readiness" action={<Button onClick={()=>setOpen(true)}><Plus size={17}/> Log service</Button>}/><div className="maintenance-summary"><div><Wrench/><span><b>{rows.filter(x=>x.status==='ACTIVE').length}</b>Active jobs</span></div><div><Check/><span><b>{rows.filter(x=>x.status==='CLOSED').length}</b>Completed services</span></div><div><CircleDollarSign/><span><b>{money(rows.reduce((s,x)=>s+x.cost,0))}</b>Total service cost</span></div></div><section className="panel records"><div className="table-wrap"><table><thead><tr><th>Vehicle</th><th>Service</th><th>Started</th><th>Cost</th><th>Status</th><th/></tr></thead><tbody>{rows.map(m=><tr key={m.id}><td><div className="entity"><span><Wrench/></span><div><b>{m.vehicle.name}</b><small>{m.vehicle.registrationNo}</small></div></div></td><td><b>{m.serviceType}</b><small>{m.description}</small></td><td>{date(m.startDate)}</td><td>{money(m.cost)}</td><td><Status value={m.status}/></td><td className="actions">{m.status==='ACTIVE'&&<button onClick={()=>close(m.id)}>Close service</button>}</td></tr>)}</tbody></table></div></section>{open&&<MaintenanceForm onClose={()=>setOpen(false)} onSaved={()=>{setOpen(false);load()}}/>}</>}
function MaintenanceForm({onClose,onSaved}:{onClose:()=>void;onSaved:()=>void}){const [vehicles,setVehicles]=useState<Vehicle[]>([]),[error,setError]=useState('');useEffect(()=>{api<Vehicle[]>('/vehicles/available').then(setVehicles)},[]);async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();try{await api('/maintenance',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});onSaved()}catch(e){setError((e as Error).message)}}return <Modal title="Create maintenance record" onClose={onClose}><form className="modal-form" onSubmit={save}>{error&&<div className="alert"><X/>{error}</div>}<Field label="Available vehicle"><select name="vehicleId" required><option value="">Select vehicle</option>{vehicles.map(v=><option value={v.id} key={v.id}>{v.name} · {v.registrationNo}</option>)}</select></Field><div className="form-grid"><Field label="Service type"><input name="serviceType" placeholder="Oil change" required/></Field><Field label="Estimated cost (₹)"><input name="cost" type="number" min="0" required/></Field></div><Field label="Description"><textarea name="description" rows={3}/></Field><div className="rule-note"><Wrench/><span>Saving this record immediately changes the vehicle status to In Shop.</span></div><div className="modal-actions"><Button type="button" variant="ghost" onClick={onClose}>Cancel</Button><Button type="submit">Start service</Button></div></form></Modal>}

function FinancePage(){const [data,setData]=useState<Finance>({fuelLogs:[],expenses:[]}),[vehicles,setVehicles]=useState<Vehicle[]>([]),[modal,setModal]=useState<'fuel'|'expense'|null>(null);const load=()=>Promise.all([api<Finance>('/finance'),api<Vehicle[]>('/vehicles')]).then(([d,v])=>{setData(d);setVehicles(v)});useEffect(()=>{load()},[]);const total=data.fuelLogs.reduce((s,x)=>s+x.cost,0)+data.expenses.reduce((s,x)=>s+x.amount,0);return <><PageTitle eyebrow="Financial operations" title="Fuel & expenses" description="Capture every rupee spent across the fleet" action={<div className="button-row"><Button onClick={()=>setModal('fuel')}><Plus size={17}/> Fuel log</Button><Button variant="ghost" onClick={()=>setModal('expense')}><Plus size={17}/> Expense</Button></div>}/><div className="finance-cards"><div><span>Total operating spend</span><b>{money(total)}</b><small>Across recorded transactions</small></div><div><span>Fuel cost</span><b>{money(data.fuelLogs.reduce((s,x)=>s+x.cost,0))}</b><small>{data.fuelLogs.reduce((s,x)=>s+x.liters,0)} liters logged</small></div><div><span>Other expenses</span><b>{money(data.expenses.reduce((s,x)=>s+x.amount,0))}</b><small>{data.expenses.length} transactions</small></div></div><div className="dashboard-grid"><section className="panel wide"><div className="panel-head"><div><span>Fuel management</span><h3>Recent fuel logs</h3></div></div><div className="table-wrap"><table><thead><tr><th>Vehicle</th><th>Date</th><th>Volume</th><th>Cost</th></tr></thead><tbody>{data.fuelLogs.map(x=><tr key={x.id}><td><b>{x.vehicle.name}</b><small>{x.vehicle.registrationNo}</small></td><td>{date(x.date)}</td><td>{x.liters} L</td><td><b>{money(x.cost)}</b></td></tr>)}</tbody></table></div></section><section className="panel"><div className="panel-head"><div><span>Expenses</span><h3>Other spend</h3></div></div>{data.expenses.map(x=><div className="expense-line" key={x.id}><span><CircleDollarSign/></span><div><b>{pretty(x.type)}</b><small>{x.vehicle.name} · {x.description}</small></div><strong>{money(x.amount)}</strong></div>)}</section></div>{modal&&<FinanceForm type={modal} vehicles={vehicles} onClose={()=>setModal(null)} onSaved={()=>{setModal(null);load()}}/>}</>}
function FinanceForm({type,vehicles,onClose,onSaved}:{type:'fuel'|'expense';vehicles:Vehicle[];onClose:()=>void;onSaved:()=>void}){async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();try{await api(type==='fuel'?'/fuel':'/expenses',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});onSaved()}catch(e){alert((e as Error).message)}}return <Modal title={type==='fuel'?'Add fuel log':'Add fleet expense'} onClose={onClose}><form className="modal-form" onSubmit={save}><Field label="Vehicle"><select name="vehicleId" required><option value="">Select vehicle</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></Field>{type==='fuel'?<div className="form-grid"><Field label="Liters"><input name="liters" type="number" step="0.1" min="0.1" required/></Field><Field label="Total cost (₹)"><input name="cost" type="number" min="1" required/></Field><Field label="Odometer (km)"><input name="odometerKm" type="number" min="1"/></Field></div>:<><div className="form-grid"><Field label="Expense type"><select name="type"><option>TOLL</option><option>REPAIR</option><option>INSURANCE</option><option>OTHER</option></select></Field><Field label="Amount (₹)"><input name="amount" type="number" min="1" required/></Field></div><Field label="Description"><input name="description"/></Field></>}<div className="modal-actions"><Button type="button" variant="ghost" onClick={onClose}>Cancel</Button><Button type="submit">Save transaction</Button></div></form></Modal>}

function Analytics(){const [data,setData]=useState<any>();useEffect(()=>{api('/analytics').then(setData)},[]);if(!data)return <Loading/>;const s=data.summary;const exportCsv=async()=>{const token=localStorage.getItem('transitops_token');const r=await fetch(`${API_URL}/analytics/export.csv`,{headers:{Authorization:`Bearer ${token}`}});const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='transitops-analytics.csv';a.click();URL.revokeObjectURL(url)};return <><PageTitle eyebrow="Performance intelligence" title="Reports & analytics" description="Turn operational data into better fleet decisions" action={<Button variant="ghost" onClick={exportCsv}><Download size={17}/> Export CSV</Button>}/><div className="analytics-cards"><div><span>Fuel efficiency</span><b>{s.fuelEfficiency.toFixed(1)} <small>km/L</small></b><i className="up">↑ Live</i></div><div><span>Fleet utilization</span><b>{s.fleetUtilization.toFixed(0)}<small>%</small></b><i>Active / operational</i></div><div><span>Operational cost</span><b>{money(s.operationalCost)}</b><i>Fuel + maintenance + expenses</i></div><div><span>Vehicle ROI</span><b>{s.vehicleRoi.toFixed(1)}<small>%</small></b><i className={s.vehicleRoi>=0?'up':'down'}>{s.vehicleRoi>=0?'Positive return':'Needs attention'}</i></div></div><div className="dashboard-grid"><section className="panel wide chart-panel"><div className="panel-head"><div><span>Cost analysis</span><h3>Operational cost by vehicle</h3></div></div><ResponsiveContainer width="100%" height={280}><BarChart data={data.byVehicle}><CartesianGrid strokeDasharray="4 4" vertical={false} stroke="#e6e9ed"/><XAxis dataKey="name" tickLine={false} axisLine={false}/><Tooltip formatter={(v:any)=>money(Number(v))}/><Bar dataKey="operationalCost" fill="#ef8f24" radius={[7,7,0,0]} barSize={42}/></BarChart></ResponsiveContainer></section><section className="panel"><div className="panel-head"><div><span>Return</span><h3>Vehicle ROI</h3></div></div><div className="roi-list">{data.byVehicle.map((x:any)=><div key={x.id}><div><b>{x.name}</b><span>{x.roi.toFixed(1)}%</span></div><i><em style={{width:`${Math.max(4,Math.min(100,Math.abs(x.roi)*5))}%`}}/></i></div>)}</div></section></div></>}
function SettingsPage({user}:{user:User}){return <><PageTitle eyebrow="Administration" title="Settings & access" description="Organization profile and role-based permissions"/><div className="settings-grid"><section className="panel settings-card"><div className="panel-head"><div><span>General</span><h3>Organization profile</h3></div></div><Field label="Company name"><input defaultValue="TransitOps India Pvt. Ltd."/></Field><Field label="Operations email"><input defaultValue="operations@transitops.in"/></Field><Field label="Default region"><select defaultValue="West"><option>West</option><option>North</option><option>South</option></select></Field><Button>Save changes</Button></section><section className="panel rbac"><div className="panel-head"><div><span>Security</span><h3>Role-based access</h3></div></div><div className="rbac-head"><span>Role</span><span>Fleet</span><span>Trips</span><span>Safety</span><span>Finance</span></div>{roles.map(r=><div className={user.role===r?'current':''} key={r}><b>{roleLabel[r]}</b><span>{['FLEET_MANAGER','DISPATCHER'].includes(r)?'✓':'View'}</span><span>{['FLEET_MANAGER','DISPATCHER'].includes(r)?'✓':'—'}</span><span>{['FLEET_MANAGER','SAFETY_OFFICER'].includes(r)?'✓':'—'}</span><span>{['FLEET_MANAGER','FINANCIAL_ANALYST'].includes(r)?'✓':'—'}</span></div>)}</section></div></>}

export default function App(){const [user,setUser]=useState<User|null>(null),[checking,setChecking]=useState(hasSession());useEffect(()=>{if(!hasSession())return;api<{user:User}>('/auth/me').then(x=>setUser(x.user)).catch(()=>setToken(null)).finally(()=>setChecking(false))},[]);if(checking)return <Loading/>;if(!user)return <Login onLogin={setUser}/>;return <Shell user={user} onLogout={()=>{setToken(null);setUser(null)}}/>}
