ALTER TABLE "Trip"
ALTER COLUMN "estimatedTollsInr" DROP DEFAULT,
ALTER COLUMN "estimatedTollsInr" DROP NOT NULL,
ADD COLUMN IF NOT EXISTS "estimatedDurationMin" INTEGER,
ADD COLUMN IF NOT EXISTS "routeSummary" TEXT,
ADD COLUMN IF NOT EXISTS "routeProvider" TEXT,
ADD COLUMN IF NOT EXISTS "tollEstimateStatus" TEXT,
ADD COLUMN IF NOT EXISTS "routeEstimatedAt" TIMESTAMP(3);
